apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tms-prototyper"
  namespace: "min-side"
  labels:
    "team": "min-side"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/internal/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}