apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tms-prototyper"
  namespace: "min-side"
  labels:
    team: "min-side"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/prototyper/api/isAlive"
    initialDelay: 20
  readiness:
    path: "/prototyper/api/isReady"
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses:
    - "https://min-side.dev.nav.no/prototyper"
